import type { Product } from "@/lib/types";

/**
 * Placeholder catalogue used until the Shopify Storefront API is wired up
 * (build-order step 8). Imagery is temporarily cropped from the Stitch design
 * comps in `design-reference/` and should be replaced with real product
 * photography before launch.
 */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "sd-001",
    slug: "helios-solitaire",
    name: "The Helios Solitaire",
    price: 4250,
    image: "/images/mock/helios-solitaire.png",
    specs: ["1.5 CT", "D COLOR", "VVS1"],
    certificate: "GIA",
    tagline: "A radiant classic, cut to catch every angle of light.",
    shape: "Round",
    carat: 1.5,
    cut: "Ideal",
    color: "D",
    clarity: "VVS1",
    metal: "18K Yellow Gold",
  },
  {
    id: "sd-002",
    slug: "aura-oval-pave",
    name: "Aura Oval Pavé",
    price: 6800,
    image: "/images/mock/aura-oval-pave.png",
    specs: ["2.0 CT", "E COLOR", "IF"],
    certificate: "HRD",
    tagline: "Pavé brilliance wrapped around a singular oval light.",
    shape: "Oval",
    carat: 2.0,
    cut: "Very Good",
    color: "E",
    clarity: "IF",
    metal: "Platinum",
  },
  {
    id: "sd-003",
    slug: "zenith-emerald",
    name: "Zenith Emerald",
    price: 5400,
    image: "/images/mock/zenith-emerald.png",
    specs: ["1.8 CT", "F COLOR", "VS1"],
    certificate: "GIA",
    tagline: "Clean lines, uncompromising clarity.",
    shape: "Emerald",
    carat: 1.8,
    cut: "Excellent",
    color: "F",
    clarity: "VS1",
    metal: "18K White Gold",
  },
  {
    id: "sd-004",
    slug: "celestial-pear",
    name: "Celestial Pear",
    price: 3950,
    image: "/images/mock/celestial-pear.png",
    specs: ["1.2 CT", "D COLOR", "VVS2"],
    certificate: "HRD",
    tagline: "A single teardrop of captured light.",
    shape: "Pear",
    carat: 1.2,
    cut: "Ideal",
    color: "D",
    clarity: "VVS2",
    metal: "18K Rose Gold",
  },
  {
    id: "sd-005",
    slug: "lumina-cushion",
    name: "Lumina Cushion",
    price: 8200,
    image: "/images/mock/lumina-cushion.png",
    specs: ["2.5 CT", "G COLOR", "VVS1"],
    certificate: "GIA",
    tagline: "Soft corners, uncompromising fire.",
    shape: "Cushion",
    carat: 2.5,
    cut: "Very Good",
    color: "G",
    clarity: "VVS1",
    metal: "18K Yellow Gold",
  },
  {
    id: "sd-006",
    slug: "radiant-bezel",
    name: "Radiant Bezel",
    price: 5100,
    image: "/images/mock/radiant-bezel.png",
    specs: ["1.7 CT", "E COLOR", "VS2"],
    certificate: "GIA",
    tagline: "Bezel-set brilliance, quietly modern.",
    shape: "Radiant",
    carat: 1.7,
    cut: "Excellent",
    color: "E",
    clarity: "VS2",
    metal: "18K White Gold",
  },
];
